
namespace Capa_de_presentacion
{
    partial class Producto
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Producto));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tbxcategoria = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txbproducto = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txbxmarca = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txbxmedida = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxcantidad = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxpc = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txbxpv = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuUserControl1 = new Bunifu.UI.WinForms.BunifuUserControl();
            this.bunifuThinButton21 = new Bunifu.Framework.UI.BunifuThinButton2();
            this.bunifuThinButton22 = new Bunifu.Framework.UI.BunifuThinButton2();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.panel1 = new System.Windows.Forms.Panel();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.guna2DragControl1 = new Guna.UI2.WinForms.Guna2DragControl(this.components);
            this.bunifuGradientPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            // 
            // tbxcategoria
            // 
            this.tbxcategoria.AcceptsReturn = false;
            this.tbxcategoria.AcceptsTab = false;
            this.tbxcategoria.AnimationSpeed = 200;
            this.tbxcategoria.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxcategoria.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxcategoria.AutoSizeHeight = true;
            this.tbxcategoria.BackColor = System.Drawing.Color.Transparent;
            this.tbxcategoria.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxcategoria.BackgroundImage")));
            this.tbxcategoria.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbxcategoria.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxcategoria.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            this.tbxcategoria.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxcategoria.BorderRadius = 30;
            this.tbxcategoria.BorderThickness = 1;
            this.tbxcategoria.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxcategoria.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxcategoria.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbxcategoria.DefaultText = "";
            this.tbxcategoria.FillColor = System.Drawing.Color.White;
            this.tbxcategoria.HideSelection = true;
            this.tbxcategoria.IconLeft = null;
            this.tbxcategoria.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxcategoria.IconPadding = 10;
            this.tbxcategoria.IconRight = null;
            this.tbxcategoria.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxcategoria.Lines = new string[0];
            this.tbxcategoria.Location = new System.Drawing.Point(17, 187);
            this.tbxcategoria.MaxLength = 32767;
            this.tbxcategoria.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxcategoria.Modified = false;
            this.tbxcategoria.Multiline = false;
            this.tbxcategoria.Name = "tbxcategoria";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxcategoria.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxcategoria.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxcategoria.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxcategoria.OnIdleState = stateProperties32;
            this.tbxcategoria.Padding = new System.Windows.Forms.Padding(3);
            this.tbxcategoria.PasswordChar = '\0';
            this.tbxcategoria.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxcategoria.PlaceholderText = "Ingrese la categoria del producto";
            this.tbxcategoria.ReadOnly = false;
            this.tbxcategoria.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxcategoria.SelectedText = "";
            this.tbxcategoria.SelectionLength = 0;
            this.tbxcategoria.SelectionStart = 0;
            this.tbxcategoria.ShortcutsEnabled = true;
            this.tbxcategoria.Size = new System.Drawing.Size(271, 39);
            this.tbxcategoria.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxcategoria.TabIndex = 0;
            this.tbxcategoria.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxcategoria.TextMarginBottom = 0;
            this.tbxcategoria.TextMarginLeft = 3;
            this.tbxcategoria.TextMarginTop = 1;
            this.tbxcategoria.TextPlaceholder = "Ingrese la categoria del producto";
            this.bunifuToolTip1.SetToolTip(this.tbxcategoria, "");
            this.bunifuToolTip1.SetToolTipIcon(this.tbxcategoria, null);
            this.bunifuToolTip1.SetToolTipTitle(this.tbxcategoria, "");
            this.tbxcategoria.UseSystemPasswordChar = false;
            this.tbxcategoria.WordWrap = true;
            // 
            // txbproducto
            // 
            this.txbproducto.AcceptsReturn = false;
            this.txbproducto.AcceptsTab = false;
            this.txbproducto.AnimationSpeed = 200;
            this.txbproducto.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbproducto.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbproducto.AutoSizeHeight = true;
            this.txbproducto.BackColor = System.Drawing.Color.Transparent;
            this.txbproducto.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbproducto.BackgroundImage")));
            this.txbproducto.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbproducto.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txbproducto.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            this.txbproducto.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbproducto.BorderRadius = 30;
            this.txbproducto.BorderThickness = 1;
            this.txbproducto.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbproducto.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbproducto.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txbproducto.DefaultText = "";
            this.txbproducto.FillColor = System.Drawing.Color.White;
            this.txbproducto.HideSelection = true;
            this.txbproducto.IconLeft = null;
            this.txbproducto.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbproducto.IconPadding = 10;
            this.txbproducto.IconRight = null;
            this.txbproducto.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbproducto.Lines = new string[0];
            this.txbproducto.Location = new System.Drawing.Point(17, 249);
            this.txbproducto.MaxLength = 32767;
            this.txbproducto.MinimumSize = new System.Drawing.Size(1, 1);
            this.txbproducto.Modified = false;
            this.txbproducto.Multiline = false;
            this.txbproducto.Name = "txbproducto";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbproducto.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbproducto.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbproducto.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbproducto.OnIdleState = stateProperties36;
            this.txbproducto.Padding = new System.Windows.Forms.Padding(3);
            this.txbproducto.PasswordChar = '\0';
            this.txbproducto.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbproducto.PlaceholderText = "Ingrese el nombre del producto";
            this.txbproducto.ReadOnly = false;
            this.txbproducto.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbproducto.SelectedText = "";
            this.txbproducto.SelectionLength = 0;
            this.txbproducto.SelectionStart = 0;
            this.txbproducto.ShortcutsEnabled = true;
            this.txbproducto.Size = new System.Drawing.Size(271, 39);
            this.txbproducto.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbproducto.TabIndex = 1;
            this.txbproducto.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbproducto.TextMarginBottom = 0;
            this.txbproducto.TextMarginLeft = 3;
            this.txbproducto.TextMarginTop = 1;
            this.txbproducto.TextPlaceholder = "Ingrese el nombre del producto";
            this.bunifuToolTip1.SetToolTip(this.txbproducto, "");
            this.bunifuToolTip1.SetToolTipIcon(this.txbproducto, null);
            this.bunifuToolTip1.SetToolTipTitle(this.txbproducto, "");
            this.txbproducto.UseSystemPasswordChar = false;
            this.txbproducto.WordWrap = true;
            // 
            // txbxmarca
            // 
            this.txbxmarca.AcceptsReturn = false;
            this.txbxmarca.AcceptsTab = false;
            this.txbxmarca.AnimationSpeed = 200;
            this.txbxmarca.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbxmarca.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbxmarca.AutoSizeHeight = true;
            this.txbxmarca.BackColor = System.Drawing.Color.Transparent;
            this.txbxmarca.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbxmarca.BackgroundImage")));
            this.txbxmarca.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbxmarca.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txbxmarca.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            this.txbxmarca.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbxmarca.BorderRadius = 30;
            this.txbxmarca.BorderThickness = 1;
            this.txbxmarca.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbxmarca.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbxmarca.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txbxmarca.DefaultText = "";
            this.txbxmarca.FillColor = System.Drawing.Color.White;
            this.txbxmarca.HideSelection = true;
            this.txbxmarca.IconLeft = null;
            this.txbxmarca.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbxmarca.IconPadding = 10;
            this.txbxmarca.IconRight = null;
            this.txbxmarca.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbxmarca.Lines = new string[0];
            this.txbxmarca.Location = new System.Drawing.Point(17, 311);
            this.txbxmarca.MaxLength = 32767;
            this.txbxmarca.MinimumSize = new System.Drawing.Size(1, 1);
            this.txbxmarca.Modified = false;
            this.txbxmarca.Multiline = false;
            this.txbxmarca.Name = "txbxmarca";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbxmarca.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbxmarca.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbxmarca.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbxmarca.OnIdleState = stateProperties40;
            this.txbxmarca.Padding = new System.Windows.Forms.Padding(3);
            this.txbxmarca.PasswordChar = '\0';
            this.txbxmarca.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbxmarca.PlaceholderText = "Ingrese la marca del producto";
            this.txbxmarca.ReadOnly = false;
            this.txbxmarca.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbxmarca.SelectedText = "";
            this.txbxmarca.SelectionLength = 0;
            this.txbxmarca.SelectionStart = 0;
            this.txbxmarca.ShortcutsEnabled = true;
            this.txbxmarca.Size = new System.Drawing.Size(271, 39);
            this.txbxmarca.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbxmarca.TabIndex = 2;
            this.txbxmarca.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbxmarca.TextMarginBottom = 0;
            this.txbxmarca.TextMarginLeft = 3;
            this.txbxmarca.TextMarginTop = 1;
            this.txbxmarca.TextPlaceholder = "Ingrese la marca del producto";
            this.bunifuToolTip1.SetToolTip(this.txbxmarca, "");
            this.bunifuToolTip1.SetToolTipIcon(this.txbxmarca, null);
            this.bunifuToolTip1.SetToolTipTitle(this.txbxmarca, "");
            this.txbxmarca.UseSystemPasswordChar = false;
            this.txbxmarca.WordWrap = true;
            // 
            // txbxmedida
            // 
            this.txbxmedida.AcceptsReturn = false;
            this.txbxmedida.AcceptsTab = false;
            this.txbxmedida.AnimationSpeed = 200;
            this.txbxmedida.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbxmedida.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbxmedida.AutoSizeHeight = true;
            this.txbxmedida.BackColor = System.Drawing.Color.Transparent;
            this.txbxmedida.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbxmedida.BackgroundImage")));
            this.txbxmedida.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbxmedida.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txbxmedida.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            this.txbxmedida.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbxmedida.BorderRadius = 30;
            this.txbxmedida.BorderThickness = 1;
            this.txbxmedida.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbxmedida.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbxmedida.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txbxmedida.DefaultText = "";
            this.txbxmedida.FillColor = System.Drawing.Color.White;
            this.txbxmedida.HideSelection = true;
            this.txbxmedida.IconLeft = null;
            this.txbxmedida.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbxmedida.IconPadding = 10;
            this.txbxmedida.IconRight = null;
            this.txbxmedida.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbxmedida.Lines = new string[0];
            this.txbxmedida.Location = new System.Drawing.Point(17, 373);
            this.txbxmedida.MaxLength = 32767;
            this.txbxmedida.MinimumSize = new System.Drawing.Size(1, 1);
            this.txbxmedida.Modified = false;
            this.txbxmedida.Multiline = false;
            this.txbxmedida.Name = "txbxmedida";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbxmedida.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbxmedida.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbxmedida.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbxmedida.OnIdleState = stateProperties44;
            this.txbxmedida.Padding = new System.Windows.Forms.Padding(3);
            this.txbxmedida.PasswordChar = '\0';
            this.txbxmedida.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbxmedida.PlaceholderText = "Ingrese la unidad de medida del producto";
            this.txbxmedida.ReadOnly = false;
            this.txbxmedida.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbxmedida.SelectedText = "";
            this.txbxmedida.SelectionLength = 0;
            this.txbxmedida.SelectionStart = 0;
            this.txbxmedida.ShortcutsEnabled = true;
            this.txbxmedida.Size = new System.Drawing.Size(271, 39);
            this.txbxmedida.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbxmedida.TabIndex = 3;
            this.txbxmedida.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbxmedida.TextMarginBottom = 0;
            this.txbxmedida.TextMarginLeft = 3;
            this.txbxmedida.TextMarginTop = 1;
            this.txbxmedida.TextPlaceholder = "Ingrese la unidad de medida del producto";
            this.bunifuToolTip1.SetToolTip(this.txbxmedida, "");
            this.bunifuToolTip1.SetToolTipIcon(this.txbxmedida, null);
            this.bunifuToolTip1.SetToolTipTitle(this.txbxmedida, "");
            this.txbxmedida.UseSystemPasswordChar = false;
            this.txbxmedida.WordWrap = true;
            // 
            // tbxcantidad
            // 
            this.tbxcantidad.AcceptsReturn = false;
            this.tbxcantidad.AcceptsTab = false;
            this.tbxcantidad.AnimationSpeed = 200;
            this.tbxcantidad.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxcantidad.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxcantidad.AutoSizeHeight = true;
            this.tbxcantidad.BackColor = System.Drawing.Color.Transparent;
            this.tbxcantidad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxcantidad.BackgroundImage")));
            this.tbxcantidad.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbxcantidad.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxcantidad.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            this.tbxcantidad.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxcantidad.BorderRadius = 30;
            this.tbxcantidad.BorderThickness = 1;
            this.tbxcantidad.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxcantidad.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxcantidad.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbxcantidad.DefaultText = "";
            this.tbxcantidad.FillColor = System.Drawing.Color.White;
            this.tbxcantidad.HideSelection = true;
            this.tbxcantidad.IconLeft = null;
            this.tbxcantidad.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxcantidad.IconPadding = 10;
            this.tbxcantidad.IconRight = null;
            this.tbxcantidad.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxcantidad.Lines = new string[0];
            this.tbxcantidad.Location = new System.Drawing.Point(17, 433);
            this.tbxcantidad.MaxLength = 32767;
            this.tbxcantidad.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxcantidad.Modified = false;
            this.tbxcantidad.Multiline = false;
            this.tbxcantidad.Name = "tbxcantidad";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxcantidad.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxcantidad.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxcantidad.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxcantidad.OnIdleState = stateProperties48;
            this.tbxcantidad.Padding = new System.Windows.Forms.Padding(3);
            this.tbxcantidad.PasswordChar = '\0';
            this.tbxcantidad.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxcantidad.PlaceholderText = "Ingrese la cantidad del producto";
            this.tbxcantidad.ReadOnly = false;
            this.tbxcantidad.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxcantidad.SelectedText = "";
            this.tbxcantidad.SelectionLength = 0;
            this.tbxcantidad.SelectionStart = 0;
            this.tbxcantidad.ShortcutsEnabled = true;
            this.tbxcantidad.Size = new System.Drawing.Size(271, 39);
            this.tbxcantidad.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxcantidad.TabIndex = 4;
            this.tbxcantidad.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxcantidad.TextMarginBottom = 0;
            this.tbxcantidad.TextMarginLeft = 3;
            this.tbxcantidad.TextMarginTop = 1;
            this.tbxcantidad.TextPlaceholder = "Ingrese la cantidad del producto";
            this.bunifuToolTip1.SetToolTip(this.tbxcantidad, "");
            this.bunifuToolTip1.SetToolTipIcon(this.tbxcantidad, null);
            this.bunifuToolTip1.SetToolTipTitle(this.tbxcantidad, "");
            this.tbxcantidad.UseSystemPasswordChar = false;
            this.tbxcantidad.WordWrap = true;
            // 
            // tbxpc
            // 
            this.tbxpc.AcceptsReturn = false;
            this.tbxpc.AcceptsTab = false;
            this.tbxpc.AnimationSpeed = 200;
            this.tbxpc.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxpc.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxpc.AutoSizeHeight = true;
            this.tbxpc.BackColor = System.Drawing.Color.Transparent;
            this.tbxpc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxpc.BackgroundImage")));
            this.tbxpc.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbxpc.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxpc.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            this.tbxpc.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxpc.BorderRadius = 30;
            this.tbxpc.BorderThickness = 1;
            this.tbxpc.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxpc.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxpc.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbxpc.DefaultText = "";
            this.tbxpc.FillColor = System.Drawing.Color.White;
            this.tbxpc.HideSelection = true;
            this.tbxpc.IconLeft = null;
            this.tbxpc.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxpc.IconPadding = 10;
            this.tbxpc.IconRight = null;
            this.tbxpc.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxpc.Lines = new string[0];
            this.tbxpc.Location = new System.Drawing.Point(17, 496);
            this.tbxpc.MaxLength = 32767;
            this.tbxpc.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxpc.Modified = false;
            this.tbxpc.Multiline = false;
            this.tbxpc.Name = "tbxpc";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxpc.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxpc.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxpc.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxpc.OnIdleState = stateProperties52;
            this.tbxpc.Padding = new System.Windows.Forms.Padding(3);
            this.tbxpc.PasswordChar = '\0';
            this.tbxpc.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxpc.PlaceholderText = "Precio de compra\r\n";
            this.tbxpc.ReadOnly = false;
            this.tbxpc.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxpc.SelectedText = "";
            this.tbxpc.SelectionLength = 0;
            this.tbxpc.SelectionStart = 0;
            this.tbxpc.ShortcutsEnabled = true;
            this.tbxpc.Size = new System.Drawing.Size(120, 39);
            this.tbxpc.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxpc.TabIndex = 5;
            this.tbxpc.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxpc.TextMarginBottom = 0;
            this.tbxpc.TextMarginLeft = 3;
            this.tbxpc.TextMarginTop = 1;
            this.tbxpc.TextPlaceholder = "Precio de compra\r\n";
            this.bunifuToolTip1.SetToolTip(this.tbxpc, "");
            this.bunifuToolTip1.SetToolTipIcon(this.tbxpc, null);
            this.bunifuToolTip1.SetToolTipTitle(this.tbxpc, "");
            this.tbxpc.UseSystemPasswordChar = false;
            this.tbxpc.WordWrap = true;
            // 
            // txbxpv
            // 
            this.txbxpv.AcceptsReturn = false;
            this.txbxpv.AcceptsTab = false;
            this.txbxpv.AnimationSpeed = 200;
            this.txbxpv.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbxpv.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbxpv.AutoSizeHeight = true;
            this.txbxpv.BackColor = System.Drawing.Color.Transparent;
            this.txbxpv.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbxpv.BackgroundImage")));
            this.txbxpv.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbxpv.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txbxpv.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            this.txbxpv.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbxpv.BorderRadius = 30;
            this.txbxpv.BorderThickness = 1;
            this.txbxpv.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbxpv.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbxpv.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txbxpv.DefaultText = "";
            this.txbxpv.FillColor = System.Drawing.Color.White;
            this.txbxpv.HideSelection = true;
            this.txbxpv.IconLeft = null;
            this.txbxpv.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbxpv.IconPadding = 10;
            this.txbxpv.IconRight = null;
            this.txbxpv.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbxpv.Lines = new string[0];
            this.txbxpv.Location = new System.Drawing.Point(168, 496);
            this.txbxpv.MaxLength = 32767;
            this.txbxpv.MinimumSize = new System.Drawing.Size(1, 1);
            this.txbxpv.Modified = false;
            this.txbxpv.Multiline = false;
            this.txbxpv.Name = "txbxpv";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbxpv.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbxpv.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(59)))), ((int)(((byte)(120)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbxpv.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbxpv.OnIdleState = stateProperties56;
            this.txbxpv.Padding = new System.Windows.Forms.Padding(3);
            this.txbxpv.PasswordChar = '\0';
            this.txbxpv.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbxpv.PlaceholderText = "Precio de venta";
            this.txbxpv.ReadOnly = false;
            this.txbxpv.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbxpv.SelectedText = "";
            this.txbxpv.SelectionLength = 0;
            this.txbxpv.SelectionStart = 0;
            this.txbxpv.ShortcutsEnabled = true;
            this.txbxpv.Size = new System.Drawing.Size(120, 39);
            this.txbxpv.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbxpv.TabIndex = 6;
            this.txbxpv.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbxpv.TextMarginBottom = 0;
            this.txbxpv.TextMarginLeft = 3;
            this.txbxpv.TextMarginTop = 1;
            this.txbxpv.TextPlaceholder = "Precio de venta";
            this.bunifuToolTip1.SetToolTip(this.txbxpv, "");
            this.bunifuToolTip1.SetToolTipIcon(this.txbxpv, null);
            this.bunifuToolTip1.SetToolTipTitle(this.txbxpv, "");
            this.txbxpv.UseSystemPasswordChar = false;
            this.txbxpv.WordWrap = true;
            // 
            // bunifuUserControl1
            // 
            this.bunifuUserControl1.AllowAnimations = false;
            this.bunifuUserControl1.AllowBorderColorChanges = false;
            this.bunifuUserControl1.AllowMouseEffects = false;
            this.bunifuUserControl1.AnimationSpeed = 200;
            this.bunifuUserControl1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuUserControl1.BackgroundColor = System.Drawing.SystemColors.Control;
            this.bunifuUserControl1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuUserControl1.BorderRadius = 1;
            this.bunifuUserControl1.BorderStyle = Bunifu.UI.WinForms.BunifuUserControl.BorderStyles.Solid;
            this.bunifuUserControl1.BorderThickness = 1;
            this.bunifuUserControl1.ColorContrastOnClick = 30;
            this.bunifuUserControl1.ColorContrastOnHover = 30;
            this.bunifuUserControl1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuUserControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuUserControl1.Image = null;
            this.bunifuUserControl1.ImageMargin = new System.Windows.Forms.Padding(0);
            this.bunifuUserControl1.Location = new System.Drawing.Point(0, 0);
            this.bunifuUserControl1.Name = "bunifuUserControl1";
            this.bunifuUserControl1.ShowBorders = true;
            this.bunifuUserControl1.Size = new System.Drawing.Size(312, 600);
            this.bunifuUserControl1.Style = Bunifu.UI.WinForms.BunifuUserControl.UserControlStyles.Flat;
            this.bunifuUserControl1.TabIndex = 7;
            this.bunifuToolTip1.SetToolTip(this.bunifuUserControl1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuUserControl1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuUserControl1, "");
            this.bunifuUserControl1.Click += new System.EventHandler(this.bunifuUserControl1_Click);
            // 
            // bunifuThinButton21
            // 
            this.bunifuThinButton21.ActiveBorderThickness = 1;
            this.bunifuThinButton21.ActiveCornerRadius = 30;
            this.bunifuThinButton21.ActiveFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuThinButton21.ActiveForecolor = System.Drawing.Color.White;
            this.bunifuThinButton21.ActiveLineColor = System.Drawing.Color.White;
            this.bunifuThinButton21.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuThinButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuThinButton21.BackgroundImage")));
            this.bunifuThinButton21.ButtonText = "Guardar";
            this.bunifuThinButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuThinButton21.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuThinButton21.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuThinButton21.IdleBorderThickness = 1;
            this.bunifuThinButton21.IdleCornerRadius = 30;
            this.bunifuThinButton21.IdleFillColor = System.Drawing.Color.White;
            this.bunifuThinButton21.IdleForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuThinButton21.IdleLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuThinButton21.Location = new System.Drawing.Point(17, 546);
            this.bunifuThinButton21.Margin = new System.Windows.Forms.Padding(5);
            this.bunifuThinButton21.Name = "bunifuThinButton21";
            this.bunifuThinButton21.Size = new System.Drawing.Size(120, 41);
            this.bunifuThinButton21.TabIndex = 8;
            this.bunifuThinButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuToolTip1.SetToolTip(this.bunifuThinButton21, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuThinButton21, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuThinButton21, "");
            this.bunifuThinButton21.Click += new System.EventHandler(this.bunifuThinButton21_Click);
            // 
            // bunifuThinButton22
            // 
            this.bunifuThinButton22.ActiveBorderThickness = 1;
            this.bunifuThinButton22.ActiveCornerRadius = 30;
            this.bunifuThinButton22.ActiveFillColor = System.Drawing.Color.Red;
            this.bunifuThinButton22.ActiveForecolor = System.Drawing.Color.White;
            this.bunifuThinButton22.ActiveLineColor = System.Drawing.Color.White;
            this.bunifuThinButton22.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuThinButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuThinButton22.BackgroundImage")));
            this.bunifuThinButton22.ButtonText = "Cancelar";
            this.bunifuThinButton22.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuThinButton22.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuThinButton22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuThinButton22.IdleBorderThickness = 1;
            this.bunifuThinButton22.IdleCornerRadius = 30;
            this.bunifuThinButton22.IdleFillColor = System.Drawing.Color.White;
            this.bunifuThinButton22.IdleForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuThinButton22.IdleLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuThinButton22.Location = new System.Drawing.Point(166, 546);
            this.bunifuThinButton22.Margin = new System.Windows.Forms.Padding(5);
            this.bunifuThinButton22.Name = "bunifuThinButton22";
            this.bunifuThinButton22.Size = new System.Drawing.Size(122, 41);
            this.bunifuThinButton22.TabIndex = 9;
            this.bunifuThinButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuToolTip1.SetToolTip(this.bunifuThinButton22, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuThinButton22, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuThinButton22, "");
            this.bunifuThinButton22.Click += new System.EventHandler(this.bunifuThinButton22_Click);
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.label1);
            this.bunifuGradientPanel1.Controls.Add(this.pictureBox2);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.DeepSkyBlue;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(78)))), ((int)(((byte)(145)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(133)))), ((int)(((byte)(213)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(312, 44);
            this.bunifuGradientPanel1.TabIndex = 11;
            this.bunifuToolTip1.SetToolTip(this.bunifuGradientPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuGradientPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuGradientPanel1, "");
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Oswald", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(99, 5);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(109, 36);
            this.label1.TabIndex = 14;
            this.label1.Text = "Productos";
            this.bunifuToolTip1.SetToolTip(this.label1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.label1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.label1, "");
            // 
            // pictureBox2
            // 
            this.pictureBox2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(274, 0);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(35, 44);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 13;
            this.pictureBox2.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.pictureBox2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.pictureBox2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.pictureBox2, "");
            this.pictureBox2.Click += new System.EventHandler(this.pictureBox2_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(225)))), ((int)(((byte)(225)))));
            this.pictureBox1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(63, 65);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(175, 106);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 12;
            this.pictureBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.pictureBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.pictureBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.pictureBox1, "");
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.Blue;
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.Black;
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = null;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 44);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(312, 5);
            this.panel1.TabIndex = 13;
            this.bunifuToolTip1.SetToolTip(this.panel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.panel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.panel1, "");
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = true;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.Screen;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // guna2DragControl1
            // 
            this.guna2DragControl1.TargetControl = this.bunifuGradientPanel1;
            // 
            // Producto
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(312, 600);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Controls.Add(this.bunifuThinButton22);
            this.Controls.Add(this.bunifuThinButton21);
            this.Controls.Add(this.txbxpv);
            this.Controls.Add(this.tbxpc);
            this.Controls.Add(this.tbxcantidad);
            this.Controls.Add(this.txbxmedida);
            this.Controls.Add(this.txbxmarca);
            this.Controls.Add(this.txbproducto);
            this.Controls.Add(this.tbxcategoria);
            this.Controls.Add(this.bunifuUserControl1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Producto";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Producto";
            this.Load += new System.EventHandler(this.Producto_Load);
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox tbxcategoria;
        private Bunifu.UI.WinForms.BunifuTextBox txbproducto;
        private Bunifu.UI.WinForms.BunifuTextBox txbxmarca;
        private Bunifu.UI.WinForms.BunifuTextBox txbxmedida;
        private Bunifu.UI.WinForms.BunifuTextBox tbxcantidad;
        private Bunifu.UI.WinForms.BunifuTextBox tbxpc;
        private Bunifu.UI.WinForms.BunifuTextBox txbxpv;
        private Bunifu.UI.WinForms.BunifuUserControl bunifuUserControl1;
        private Bunifu.Framework.UI.BunifuThinButton2 bunifuThinButton21;
        private Bunifu.Framework.UI.BunifuThinButton2 bunifuThinButton22;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Panel panel1;
        private Guna.UI2.WinForms.Guna2DragControl guna2DragControl1;
    }
}